### ISSUE TITLE
how to set StanfordCoreNLP

### ISSUE THREAD

**Issue by KIDxiaoyuan** [JosephPai/Art-Description#2]
how to set StanfordCoreNLP in nlp = StanfordCoreNLP('/data00/user1/data/corenlp/')

**Comment by JosephPai** [comment]
Please refer to [python-stanford-corenlp](https://github.com/stanfordnlp/python-stanford-corenlp)

**Comment by KIDxiaoyuan** [comment]
thx,it worked，but new question happend.in caption_one.py Line 87 
# Add new words to sequences
            seqs = torch.cat([seqs[prev_word_inds], next_word_inds.unsqueeze(1)], dim=1)  # (s, step+1)
IndexError: tensors used as indices must be long, byte or bool tensors
i found 
top_k_words is tensor([  1,  18, 107,   2,  11], device='cuda:0') 
vocab_size is 10781
prev_word_inds : tensor([9.2756e-05, 1.6696e-03, 9.9249e-03, 1.8551e-04, 1.0203e-03],
       device='cuda:0')
seqs: tensor([[10779],
        [10779],
        [10779],
        [10779],
        [10779]], device='cuda:0')
i think something wrong wtih prev_word_inds,and am not sure the step 
prev_word_inds = top_k_words / vocab_size  # (s)
mean.
how to fix it

**Comment by KIDxiaoyuan** [comment]
can i use 
`prev_word_inds = prev_word_inds.type(torch.long)`
?

**Comment by JosephPai** [comment]
For meaning of `prev_word_inds = top_k_words / vocab_size # (s)`, you can look into [https://github.com/sgrvinod/a-PyTorch-Tutorial-to-Image-Captioning](https://github.com/sgrvinod/a-PyTorch-Tutorial-to-Image-Captioning) for detailed explanation.

As for the error you encountered, I guess it is caused by the python version or pytorch version difference. Maybe you can first try `top_k_words // vocab_size`.
